version: 2.1
orbs:
  doppler-circleci: ft-circleci-orbs/doppler-circleci@1.4
  node: circleci/node@5.2.0
workflows:
  build:
    jobs:
      - build:
          context:
            - djd-npm-publish
jobs:
  build:
    working_directory: ~/project
    executor:
      name: node/default
      tag: '20.11-browsers'
    steps: 
      - checkout
      - doppler-circleci/install
      - add-npm-tokens
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: ESLint
          command: ./node_modules/.bin/eslint -- .
      - run:
          name: Compile with babel
          command: npm run build
      - store_artifacts:
          path: dist/
      - run:
          name: Maybe publish to npm
          command: |
            if [ "${CIRCLE_BRANCH}" == "main" ]; then
              npm publish
            fi
commands:
  add-npm-tokens:
    steps:
      - doppler-circleci/load_secrets:
          doppler_token: DOPPLER_TOKEN
      - run:
          name: Add npm token
          command: |
            npm set @financial-times:registry=https://registry.npmjs.org
            npm set //registry.npmjs.org/:_authToken=${NPM_TOKEN}