version: 2.1
orbs:
  doppler-circleci: ft-circleci-orbs/doppler-circleci@1.4
  node: circleci/node@5.2.0
workflows:
  version: 2
  build-and-release:
    jobs:
      - install:
          filters: 
            tags: 
              only: /.*/
      - release_npm:
          context:
            - djd-npm-publish
          requires: 
            - test
          filters: 
            tags: 
              only: /^v.*/
            branches: 
              ignore: /.*/
jobs:
  install:
    working_directory: ~/project
    executor:
      name: node/default
      tag: '20.11-browsers'
    steps: 
      - checkout
      - doppler-circleci/install
      - add-npm-tokens
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: ESLint
          command: ./node_modules/.bin/eslint -- .
  release_npm: 
    steps: 
      - run:
          name: Setup npm credentials
          command: echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > ${HOME}/.npmrc
      - run:
          name: Generate build
          command: npm run build        
      - run:
          name: Publish to NPM
          command: |
            if [[ $CIRCLE_TAG =~ canary ]]
            then
              npm publish --access public --tag canary
            else
              npm publish --access public --tag latest
            fi

commands:
  add-npm-tokens:
    steps:
      - doppler-circleci/load_secrets:
          doppler_token: DOPPLER_TOKEN
      - run:
          name: Add npm token
          command: |
            npm set @financial-times:registry=https://registry.npmjs.org
            npm set //registry.npmjs.org/:_authToken=${NPM_TOKEN}