version: 2.1
orbs:
  node: circleci/node@5.2.0
workflows:
  version: 2
  build:
    jobs: 
      - build
jobs:
  build:
    working_directory: ~/project
    executor:
      name: node/default
      tag: '20.11-browsers'
    steps: 
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: ESLint
          command: ./node_modules/.bin/eslint -- .
      - run:
          name: Compile with babel
          command: npm run build
      - store_artifacts:
          path: dist/
      - run:
          name: Maybe publish to npm
          command: |
            if [ "${CIRCLE_BRANCH}" == "main" ]; then
              echo -e "$NPM_USERNAME\n$NPM_PASSWORD\n$NPM_EMAIL" | npm login
              ./node_modules/.bin/publish
            fi