version: 2.1
orbs:
  node: circleci/node@5.2.0
workflows:
  version: 2
  build-deploy:
    jobs:
      - checkout-install:
          checkout: true
          commands: 
            - run: 
                command: npm install
      - compile:
          requires:
            - checkout-install
          commands:
            - run:
                name: ESLint
                command: ./node_modules/.bin/eslint -- .
            - run:
                name: Compile with babel
                command: npm run build
      - store_artifacts:
          requires:
            - compile
          path: dist/
      - deploy:
          requires:
            - store_artifacts
          filters:
            branches:
              only: main
          commands:
            - run:
                name: Maybe publish to npm
                command: |
                  if [ "${CIRCLE_BRANCH}" == "main" ]; then
                    echo -e "$NPM_USERNAME\n$NPM_PASSWORD\n$NPM_EMAIL" | npm login
                    ./node_modules/.bin/publish
                  fi
