version: 2.1
orbs:
  doppler-circleci: ft-circleci-orbs/doppler-circleci@1.4
  node: circleci/node@5.2.0
references:
  default_container_config: &default_container_config
    executor:
      name: node/default
      tag: '20.11-browsers'
  attach_workspace: &attach_workspace
    attach_workspace:
      at: ~/project
jobs:
  install:
    <<: *default_container_config
    steps: 
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: ESLint
          command: ./node_modules/.bin/eslint -- .
  release_npm: 
    <<: *default_container_config
    steps: 
      - *attach_workspace
      - doppler-circleci/install
      - doppler-circleci/load_secrets:
          doppler_token: DOPPLER_TOKEN
      - run:
          name: Add npm token
          command: |
            npm set @financial-times:registry=https://registry.npmjs.org
            npm set //registry.npmjs.org/:_authToken=${NPM_TOKEN}
      - run:
          name: Generate build
          command: npm run build        
      - run:
          name: Publish to NPM
          command: |
            if [[ $CIRCLE_TAG =~ canary ]]
            then
              npm publish --access public --tag canary
            else
              npm publish --access public --tag latest
            fi
workflows:
  version: 2
  build-and-release:
    jobs:
      - install:
          filters: 
            tags: 
              only: /.*/
      - release_npm:
          context:
            - djd-npm-publish
          requires: 
            - install
          filters: 
            tags: 
              only: /^v.*/
            branches: 
              ignore: /.*/